name: Предложить улучшение
description: Новая функция или изменение поведения
title: "[Идея] "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Какую задачу нужно решить
    validations:
      required: true
  - type: textarea
    attributes:
      label: Предлагаемое решение
    validations:
      required: true
  - type: textarea
    attributes:
      label: Альтернативы
